import React from "react";
import { api } from "../api/client";
import { usePolling } from "../hooks/usePolling";
import { Panel, LoadingBlock, ErrorBlock, StatusStrip } from "../components/ui";

const PROVENANCE_LABELS: Record<string, { label: string; color: string; desc: string }> = {
  VERIFIED_PUBLIC_DATA: { label: "Verified Public Data", color: "text-polar-green", desc: "Sourced from public NCPOR/Ministry of Earth Sciences references (station identity, region, approximate coordinates)." },
  SIMULATION: { label: "Simulation", color: "text-polar-amber", desc: "Generated by the software-only physics model in this app — no physical sensors exist behind it." },
  MODEL_DERIVED: { label: "Model-Derived", color: "text-polar-blue", desc: "Computed by a statistical/ML model (forecasting, equipment health, power quality) from simulated inputs." },
  DERIVED: { label: "Derived", color: "text-polar-purple", desc: "Calculated directly from other values already in the system (e.g. risk score, contribution percentages)." },
  UNAVAILABLE: { label: "Unavailable", color: "text-polar-dim", desc: "No data source exists for this — not shown, or explicitly marked as such." },
};

export default function DataAssumptionsPage() {
  const { data: stations, error, loading, refresh } = usePolling(() => api.listStations(), 30000);

  if (loading && !stations) return <LoadingBlock label="Loading data provenance..." />;
  if (error) return <ErrorBlock message={error} onRetry={refresh} />;

  const provenance = stations.data_provenance || {};

  return (
    <div className="space-y-4">
      <StatusStrip items={[
        { label: "STATIONS", value: "MAITRI / BHARATI" },
        { label: "PROVENANCE CATEGORIES", value: Object.keys(provenance).length },
      ]} />

      <Panel title="Data Provenance — What's Real vs. Simulated">
        <p className="text-sm text-polar-dim mb-4">
          POLAR-AI is a software-only engineering decision-support prototype. It does not have access to, and
          never claims to have, real-time electrical telemetry from Maitri or Bharati. This page explains
          exactly which parts of the system are real and which are modeled.
        </p>
        <div className="space-y-3">
          {Object.entries(provenance).map(([key, value]: any) => {
            const meta = PROVENANCE_LABELS[value] || { label: value, color: "text-polar-text", desc: "" };
            return (
              <div key={key} className="border border-polar-border rounded-lg p-3 flex justify-between items-start gap-4">
                <div>
                  <div className="font-semibold text-sm capitalize">{key.replace(/_/g, " ")}</div>
                  <div className="text-xs text-polar-dim mt-0.5">{meta.desc}</div>
                </div>
                <span className={`text-xs font-bold shrink-0 ${meta.color}`}>{meta.label}</span>
              </div>
            );
          })}
        </div>
      </Panel>

      <Panel title="Station Reference Information (Verified Public Data)">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {stations.stations.map((s: any) => (
            <div key={s.code} className="border border-polar-border rounded-lg p-3">
              <div className="font-bold">{s.full_name}</div>
              <div className="text-xs text-polar-dim mt-1">{s.region}</div>
              <div className="text-xs text-polar-dim">{s.coordinates}</div>
              <div className="text-xs text-polar-dim">Established: {s.established}</div>
              <p className="text-xs mt-2">{s.description}</p>
            </div>
          ))}
        </div>
        <p className="text-[10px] text-polar-dim mt-3">
          Source references: NCPOR station pages (ncpor.res.in) and Ministry of Earth Sciences public materials.
          All other station state (weather, energy, battery, diesel, risk, equipment health) is simulated.
        </p>
      </Panel>

      <Panel title="Key Assumptions">
        <ul className="text-sm space-y-2">
          <li>• Diesel emissions factor: 2.68 kg CO₂ per litre combusted (standard published figure).</li>
          <li>• Diesel generator efficiency: 3.5 kWh delivered per litre of fuel (configurable demo parameter).</li>
          <li>• Battery round-trip efficiency: 95% charge / 95% discharge.</li>
          <li>• Forecasts persist the latest observed weather rather than predicting new weather — a documented
              simplification appropriate for short-horizon energy forecasting, not a claim of real meteorological skill.</li>
          <li>• Power Quality figures (voltage/frequency/THD/etc.) are model-derived from dispatch state, not
              measured by any physical meter.</li>
          <li>• "30 Day" analytics/history views show the full available simulated window (up to 7 days since
              station startup) rather than fabricating older data.</li>
        </ul>
      </Panel>
    </div>
  );
}
